ClassSchedule/Controllers/ClassController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using ClassSchedule.Models;

namespace ClassSchedule.Controllers
{
    public class ClassController : Controller
    {
        private Repository<Class> classes { get; set; }
        private Repository<Teacher> teachers { get; set; }
        private Repository<Day> days { get; set; }

        public ClassController(ClassScheduleContext ctx)
        {
            classes = new Repository<Class>(ctx);
            teachers = new Repository<Teacher>(ctx);
            days = new Repository<Day>(ctx);
        }

        public RedirectToActionResult Index() => RedirectToAction("Index", "Home");

        [HttpGet]
        public ViewResult Add()
        {
            this.LoadViewBag("Add");
            return View();
        }

        [HttpGet]
        public ViewResult Edit(int id)
        {
            this.LoadViewBag("Edit");
            var c = this.GetClass(id);
            return View("Add", c);
        }

        [HttpPost]
        public IActionResult Add(Class c)
        {
            if (ModelState.IsValid) {
                if (c.ClassId == 0)
                    classes.Insert(c);
                else
                    classes.Update(c);
                classes.Save();
                return RedirectToAction("Index", "Home");
            }
            else {
                string operation = (c.ClassId == 0) ? "Add" : "Edit";
                this.LoadViewBag(operation);
                return View();
            }
        }

        [HttpGet]
        public ViewResult Delete(int id)
        {
            var c = this.GetClass(id);
            return View(c);
        }

        [HttpPost]
        public RedirectToActionResult Delete(Class c)
        {
            classes.Delete(c);
            classes.Save();
            return RedirectToAction("Index", "Home");
        }

        // private helper methods
        private Class GetClass(int id)
        {
            var classOptions = new QueryOptions<Class> {
                Includes = "Teacher, Day",
                Where = c => c.ClassId == id
            };
            return classes.Get(classOptions);
        }
        private void LoadViewBag(string operation)
        {
            ViewBag.Days = days.List(new QueryOptions<Day> {
                OrderBy = d => d.DayId
            });
            ViewBag.Teachers = teachers.List(new QueryOptions<Teacher> {
                OrderBy = t => t.LastName
            });
            ViewBag.Operation = operation;
        }
    }
}

ClassSchedule/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ClassSchedule.Models;

namespace ClassSchedule.Controllers
{
    public class HomeController : Controller
    {
        private Repository<Class> classes { get; set; }
        private Repository<Day> days { get; set; }

        public HomeController(ClassScheduleContext ctx) {
            classes = new Repository<Class>(ctx);
            days = new Repository<Day>(ctx);
        }

        public ViewResult Index(int id)
        {
            // options for Days query
            var dayOptions = new QueryOptions<Day> { 
                OrderBy = d => d.DayId
            };

            // options for Classes query
            var classOptions = new QueryOptions<Class> {
                Includes = "Teacher, Day"
            };
            // order by Day and then by time if no filter. Otherwise, filter by day and order by time.
            if (id == 0) {
                classOptions.OrderBy = c => c.DayId;
                classOptions.ThenOrderBy = c => c.MilitaryTime;
            }
            else {
                classOptions.Where = c => c.DayId == id;
                classOptions.OrderBy = c => c.MilitaryTime;
            }

            // execute queries
            ViewBag.Days = days.List(dayOptions);
            return View(classes.List(classOptions));
        }
    }
}

ClassSchedule/Views/Home/Index.cshtml
@model IEnumerable<Class>

@{
    ViewData["Title"] = "Class Schedule";

    // get value of id route segment
    int id = Convert.ToInt32(ViewContext.RouteData.Values["id"]);  
}

<div class="text-center">
    <h1 class="display-4">Class Schedule</h1>

    @* create links to filter classes by day, mark selected day with 'btn-dark' css class *@
    @foreach (Day d in ViewBag.Days)
    {
        string btnCss = (id == d.DayId) ? "btn btn-dark" : "btn btn-outline-dark";
        <a asp-action="Index" asp-route-id="@d.DayId" class="@btnCss mr-1 mb-2">@d.Name</a>
    }
</div>

<a asp-action="Add" asp-controller="Class" class="ml-3">Add Class</a>

<table class="table">
    <thead>
        <tr><th>Title</th><th>Number</th><th>Teacher</th><th>Day</th><th>Time</th><th></th></tr>
    </thead>
    <tbody>
        @foreach (Class c in Model) {
        <tr>
            <td>@c.Title</td>
            <td>@c.Number</td>
            <td>@c.Teacher.FullName</td>
            <td>@c.Day.Name</td>
            <td>@c.MilitaryTime</td>
            <td>
                <a asp-action="Edit" asp-controller="Class" asp-route-id="@c.ClassId"
                   class="btn btn-outline-dark">Edit</a>
                <a asp-action="Delete" asp-controller="Class" asp-route-id="@c.ClassId"
                   class="btn btn-outline-dark">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>